using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CS_Heso : MonoBehaviour
{
    private const int TotalValues = 65536;
    private const int WinningValues = 6553;

    readonly int MAX_STOCK = 4;
    public List<int[]> stock = new List<int[]>();
    [SerializeField]
    GameObject[] stockObjects = null;

    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

    }

    // 抽選メソッド
    void Lottery()
    {
        if (stock.Count < MAX_STOCK) // == から < に変更。MAX_STOCK未満の場合に追加する
        {
            int randomValue = Random.Range(0, TotalValues);
            // 当たり判定
            if (randomValue < WinningValues)
            {
                Debug.Log("当たり！");
                var i = new int[] { 1, 1, 1, };
                stock.Add(i);
            }
            else
            {
                Debug.Log("ハズレ");
                var i = new int[] { Random.Range(1, 9), Random.Range(1, 9), Random.Range(1, 9), };
                stock.Add(i);
            }
            

            foreach (var v in stockObjects)
            {
                if (!v.activeInHierarchy)
                {
                    v.SetActive(true); // 非アクティブなオブジェクトをアクティブにする
                    break;
                }
            }
        }
    }

    // ストックを無効化するメソッド
    public void DisableStock()
    {
        //if (stock.Count > 0) // ストックがある場合のみ削除
        //{
        //    stock.RemoveAt(0);
        //}
        //else
        //{
        //    Debug.LogWarning("ストックが空です");
        //}

        // stockObjectsの配列サイズをチェックしてループ
        for (int i = stockObjects.Length; i > 0; i--)
        {
            if (i - 1 >= 0 && stockObjects[i - 1].activeInHierarchy)
            {
                stockObjects[i - 1].SetActive(false); // アクティブなオブジェクトを非アクティブにする
                break;
            }
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.CompareTag("Pachinko Ball"))
        {
            Debug.Log("BallがPlaneを通過しました");
            // コルーチンが実行されていない、かつheso.stock.Countが0ではない場合、コルーチンを開始する
            Lottery();
        }
    }
}
